import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoidContextProvider from "./recoilContextProvider";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
          <script src="https://www.google.com/recaptcha/enterprise.js?render=6LeCTVQpAAAAAO_BGbVsNvtOSrl3JlRna_zBt8xn"></script>
        </head>
      <body className={inter.className }>
        <RecoidContextProvider>{children}</RecoidContextProvider>
      </body>
    </html>
  )
}
